### ISSUE TITLE
Discussion about the French version

### ISSUE THREAD

**Issue by aroberge** [aroberge/avantpy#4]
Below, I give some rationale about some choices made for the French dialect.

= = =
Pour plusieurs des mots-clés dans la version française, j'ai choisi d'utiliser un verbe à l'infinitif et de ne pas traduire le mot anglais utilisé par Python, mais plutôt de trouver un verbe qui capturait mieux l'idée à transmettre aux débutants; par exemple, `afficher` pour `print`, ou `demander` pour `input`. Je ne suis pas certain mes choix soient nécessairement les meilleurs et je serais intéressé d'entendre vos suggestions.

Les traductions que j'ai faites pour les fameux tracebacks ne sont que des premières ébauches, qui pourront certainement être améliorées.

Vous pouvez ajouter vos commentaires ou suggestions ci-dessous.

**Comment by cblegare** [comment]
Je m'interrogeais sur le choix de `pour` et j'ai pensé que de voir des alternatives nourrirait la discussion

```
liste = [mot.upper() pour mot dans paragraphe]

pour mot dans paragraphe:
    afficher(mot)

liste = [mot.upper() chaque mot dans paragraphe]

chaque mot dans paragraphe:
    afficher(mot)

iste = [mot.upper() chaque mot de paragraphe]

pour mot de paragraphe:
    afficher(mot)

liste = [mot.upper() pourchaque mot dans paragraphe]

pourchaque mot dans paragraphe:
    afficher(mot)

liste = [mot.upper() pourchaque mot de paragraphe]

pourchaque mot de paragraphe:
    afficher(mot)
```

**Comment by cblegare** [comment]
`cède` (`yield`) est impératif

Je ne suis pas contre, mais c'est incohérent avec `retourner` par exemple

**Comment by aroberge** [comment]
J'aime bien `pourchaque`. Je crois que c'est effectivement mieux que simplement `pour`.  Et je dois avouer que je n'y aurais jamais pensé ... et pourtant ....

Donc, si je traduis quelques autres exemples que j'avais dans un [autre document](https://github.com/aroberge/avantpy/blob/master/psf/idea.md#items-in-a-collection):
```py
pourchaque chiffre dans [1, 2, 3]:
    afficher(chiffre)    # ou faire autre chose

# iterating over a string:
pourchaque lettre dans "Python":
    afficher(lettre)

# iterating over the keys of a dict
pourchaque clé dans {'a': 1, 'b': 2, 'c': 3}:
    afficher(clé)

# etc
```
ce qui, je crois, se lit effectivement mieux - même si c'est un peu plus long à écrire.

`chaque` serait possiblement mieux que `pour` ... mais je crois que la combinaison des deux est meilleure et faciliterait le passage à Python pour les francophones qui apprendraient à traduire du dialecte français et connaîtraient déjà le mot `for`  (Ils apprécieraient probablement davantage de n'avoir à n'écrire qu'un mot de 3 lettres au lieu de 10.)

Pour ce qui est de `cède`, la première version que j'avais utilisais l'impératif partout ... ce qui, dans certains cas, ne me paraissait pas correct.  J'ai oublier de changer `cède` à  `céder`

Finalement, `de` est déjà utilisé comme traduction de `from`, et ne pourrait pas faire double emploi.

**Comment by maparent** [comment]
`None`... Je m'étonne de voir `Aucun` plutôt que `Rien`.
Une grosse difficulté: `not is`=>`pas est`...

**Comment by aroberge** [comment]
@maparent La traduction anglaise normale est "nothing" = "rien"; "none" = "aucun"

Également, en Python, on écrirait de préférence `is not` et donc `est pas` et non pas l'inverse.
https://www.python.org/dev/peps/pep-0008/#programming-recommendations

**Comment by maparent** [comment]
bon point pour `is not`. 
Mais je crois que le sens intuitif de l'utilisation de `None` en python est plus proche de `Rien` que de `Aucun`. `Aucun` est un déterminant, et appelle la question: aucun quoi? (Avec un sous-entendu de dénombrement) Alors que les comparaisons avec `None` vérifie que ce qui est comparé est indéfini, et n'a rien à voir avec une cardinalité.
Example: `si (a est Aucun)` vs `si (a est Rien)`... on ne dit pas qu'il n'y a aucun `a` parmi plusieurs `a` possibles.
En fait, on pourrait défendre `Indéfini` comme traduction, mais c'est lourd.
Je crois d'ailleurs également que `Nothing` serait plus clair que `None` en anglais, mais peut-être qu'on a préféré `None` pour des raisons de brièveté.

**Comment by aroberge** [comment]
Merci pour les commentaires, je vais définitivement garder l'idée de `Rien` en tête.  Je suis entièrement d'accord que `Indéfini` serait très lourd. De plus, ceci serait possiblement une contradiction en Python: un nom "indéfini" donne lieu à une exception du type `NameError`.

 Pour l'instant, je ne change **rien**, mais je prévois garder cette discussion ouverte assez longtemps pour recevoir autant de rétroactions que possible. Si plusieurs personnes se prononcent sur le meilleur mot à choisir, et qu'une majorité recommande `Rien`, je ferai probablement le changement. Idéalement, j'aimerais entendre la perspective des personnes qui utiliseront AvantPy avec des débutants ... mais ça risque de prendre un certain temps avant que quelqu'un décide de l'utiliser plutôt que d'utiliser Python: la plupart des francophones (certainement ceux de notre pays) connaissent suffisamment d'anglais pour comprendre rapidement le vocabulaire Python.

**Comment by aroberge** [comment]
En réfléchissant davantage ... en informatique, on retrouve soit `nil`, `null`, ou `none` (avec ou sans majuscules) pour ce concept.  En pensant à ces autres termes en anglais, je crois que `Nul` pourrait également être un choix possible en français...

**Comment by maparent** [comment]
Dois-je rappeler que `nil` est le mot latin pour `rien` (emprunté par l'anglais)? :->

**Comment by maparent** [comment]
Blague à part, je crois qu'on risque des lazzis autour de `monTruc est Nul`. J'approuve complètement l'idée de parler à des enseignants, par ailleurs.

**Comment by maparent** [comment]
Une autre option: `si (monTruc est Vide)`. Je continue à préférer `Rien` mais je crois que `Vide` est défendable.

**Comment by aroberge** [comment]
On est d'accord pour dire que, en Python, 

```py
if some_variable is None
```
 ne veut pas dire la même chose que 
```py
if some_variable == []
```

Avec le choix de `Vide`, on pourrait écrire  `si ma_liste est Vide`  ... ce qui porterait définitivement à confusion en comparant `si ma_liste == []`

**Comment by maparent** [comment]
en relisant plus haut sur le double emploi de `de`: vous pourriez écrire `depuis x importer y`. Un peu plus lourd, mais il me semble que `de` est peut-être un mot trop ubiquitaire pour un usage aussi spécialisé.
(mais je continue à préférer comme vous `dans` à `de` pour traduire `in`.)

**Comment by aroberge** [comment]
Ce projet est mis en hibernation pour une période indéterminée.
